# BossLiveMapMod configuration
ShowNearbyEnemies=False
ShowAllEnemies=True
ShowLivePositions=False
ShowMarkers=True
ShowBossList=True
ShowNearbyOnly=False
Transparency=1.00
UiScale=1.00
UiScaleAuto=True
