# BossLiveMapMod configuration
ShowNearbyEnemies=False
ShowAllEnemies=False
ShowLivePositions=False
ShowMarkers=True
ShowBossList=True
ShowNearbyOnly=False
ShowMarkerNames=True
Transparency=1.00
UiScale=1.00
UiScaleAuto=True
BossFontScale=1.50
