# BossLiveMapMod configuration
ShowNearbyEnemies=False
ShowAllEnemies=False
ShowLivePositions=True
ShowMarkers=True
ShowBossList=True
ShowNearbyOnly=False
ShowMarkerNames=True
Transparency=1.00
UiScale=1.00
UiScaleAuto=True
BossFontScale=2.00
